SELECT * FROM TCURSO;
SELECT * FROM TALUNO;

ALTER TABLE TALUNO ADD ESTADO CHAR(2) DEFAULT 'RS';

ALTER TABLE TALUNO ADD SALÁRIO NUMBER(8,2) DEFAULT 620;

ALTER TABLE TALUNO RENAME COLUMN SALÁRIO TO SALARIO;

UPDATE TALUNO SET
ESTADO = 'AC',
SALARIO = '250'
WHERE COD_ALUNO = 20;

UPDATE TALUNO SET
ESTADO = 'AM',
SALARIO = 2000
WHERE COD_ALUNO = 3;

UPDATE TALUNO SET
COD_ALUNO = 1,
WHERE 'NOME' = 'EMERSON';

INSERT INTO TALUNO VALUES(4,'SANDRIANE','MANAUS','69028347','AM',3000);
INSERT INTO TALUNO VALUES(5,'LETICIA','ITACOATIARA','3884848','AM',2300);
INSERT INTO TALUNO VALUES(6,'EMILLY','MANAUS','578768494','AM',1500);
INSERT INTO TALUNO VALUES(7,'MARIA','RIO BRANCO','69848809','AC',800);
INSERT INTO TALUNO VALUES(8,'PAULO','MANAUS','4577759','AM',590);
INSERT INTO TALUNO VALUES(SEQ_ALUNO.NEXTVAL,'FATIMA','JANAUACA','4555433','AM',780);

CREATE SEQUENCE SEQ_ALUNO START WITH 9;

SELECT * FROM TALUNO
WHERE ESTADO <> 'RS'
AND SALARIO <= 800
ORDER BY SALARIO DESC;

SELECT ESTADO, SALARIO, NOME FROM TALUNO
ORDER BY ESTADO, SALARIO DESC;


ALTER TABLE TALUNO ADD NASCIMENTO DATE DEFAULT SYSDATE - 1000;

SELECT SYSDATE - 100 FROM DUAL;


SELECT COD_ALUNO, NASCIMENTO, Trunc(NASCIMENTO) AS NASCIMENTO, NOME
FROM TALUNO
WHERE Trunc(NASCIMENTO) = '05/08/2015';

SELECT COD_ALUNO, NASCIMENTO, Trunc(NASCIMENTO), NOME
FROM TALUNO
WHERE NASCIMENTO
BETWEEN To_Date('05/08/2015 14:33','DD/MM/YYYY HH24:MI')
AND To_Date('05/08/2015 23:33','DD/MM/YYYY HH24:MI');

SELECT COD_CONTRATO, DATA, TOTAL, DESCONTO, DESCONTO + 1000 AS CALCULO
FROM TCONTRATO
WHERE TOTAL <= DESCONTO + 1000;

SELECT DESCONTO
FROM TCONTRATO
WHERE DESCONTO IS NOT NULL;

SELECT DESCONTO
FROM TCONTRATO
WHERE DESCONTO BETWEEN 0 AND 10;

SELECT DESCONTO, Nvl(DESCONTO,0)
FROM TCONTRATO
WHERE Nvl(DESCONTO,0) BETWEEN 0 AND 10;


SELECT * FROM TCONTRATO
WHERE DESCONTO >= 0
AND DESCONTO <= 10;

SELECT * FROM TCONTRATO
WHERE DESCONTO BETWEEN 0 AND 10;


SELECT COD_CONTRATO, TOTAL, DESCONTO, Nvl(DESCONTO,0)
FROM TCONTRATO
WHERE Nvl(DESCONTO,0) BETWEEN 0 AND 10;

SELECT * FROM TCONTRATO
WHERE DESCONTO >= 0
AND DESCONTO <= 10
OR DESCONTO = NULL;


SELECT * FROM TCONTRATO;
SELECT * FROM TALUNO;

COMMIT;

SELECT * FROM TCONTRATO;

UPDATE TCONTRATO SET
DESCONTO = NULL
WHERE COD_CONTRATO = 2;

SELECT * FROM TCURSO
WHERE COD_CURSO IN (1,2,4);

SELECT * FROM TCURSO;

SELECT * FROM TCURSO
WHERE COD_CURSO NOT IN (SELECT COD_CURSO FROM TITEM);

SELECT * FROM TCURSO
WHERE COD_CURSO IN (SELECT COD_CURSO FROM TITEM);



CREATE TABLE TITEM(
  COD_ITEM INTEGER NOT NULL PRIMARY KEY,
  ITEM  VARCHAR(30)
);

ALTER TABLE TITEM ADD DOC_CURSO VARCHAR(30);
CREATE SEQUENCE SEQ_ITEM START WITH 1;

INSERT INTO TITEM VALUES(SEQ_ITEM.NEXTVAL,'CURSO 1','09929921');
INSERT INTO TITEM VALUES(SEQ_ITEM.NEXTVAL,'CURSO 2','19929922');
INSERT INTO TITEM VALUES(SEQ_ITEM.NEXTVAL,'CURSO 3','29929923');
INSERT INTO TITEM VALUES(SEQ_ITEM.NEXTVAL,'CURSO 4','39929924');
INSERT INTO TITEM VALUES(SEQ_ITEM.NEXTVAL,'CURSO 4','49929925');

SELECT * FROM TITEM;

SELECT * FROM TCURSO WHERE NOME LIKE 'O%';

SELECT * FROM TCURSO WHERE NOME LIKE '%O';

SELECT * FROM TCURSO WHERE NOME LIKE '%O%';

ALTER TABLE TCURSO ADD PRE_REC INTEGER;
SELECT * FROM TCURSO;

UPDATE TCURSO SET
PRE_REQ = 1
WHERE COD_CURSO = 4;

ALTER TABLE TCURSO RENAME COLUMN PRE_REC TO PRE_REQ;

SELECT * FROM TCURSO
WHERE (VALOR > 750
OR VALOR < 1000)
AND CARGA_HORARIA = 25;



COMMIT;

