--CAPÍTULO 11 -- 22/06/2018

--CRIANDO UMA VIEW
CREATE OR REPLACE VIEW V_ALUNO
AS
  SELECT COD_ALUNO AS CODIGO,
         SALARIO,
         NOME AS ALUNO,
         ESTADO,
         CIDADE
  FROM TALUNO
  WHERE ESTADO = 'RS';
  --SELECT QUE REPRESENTA ESSA VIEW

--USANDO A VIEW
SELECT * FROM V_ALUNO
ORDER BY ALUNO;

--VIEW CONTRATO_TOP
CREATE OR REPLACE VIEW V_CONTRATO_TOP
AS
  SELECT COD_CONTRATO, DESCONTO
  FROM TCONTRATO
  WHERE DESCONTO >= 10;

--USANDO A VIEW CONTRATO_TOP
SELECT * FROM V_CONTRATO_TOP;

--NOME E CONTEÚDO DAS VIEWS
SELECT VIEW_NAME, TEXT
FROM USER_VIEWS;--VIEW QUE MOSTRA OUTRAS VIEWS.

--VIEW COM PARÂMETRO DE SAÍDA
CREATE OR REPLACE VIEW V_ALUNO2(COD, ALUNO, SAL)
AS
  SELECT COD_ALUNO, NOME, SALARIO
  FROM TALUNO;

SELECT * FROM V_ALUNO2;

--VIEW COMPLEXA - A CARACTERISTICA DESSA VIEW QUE A FAZ SER COMPLEXA, NAO QUE SEJA COMPLEXA
CREATE OR REPLACE VIEW V_CONTRATO
AS
  SELECT Trunc(DATA) AS DATA,
         Max(DESCONTO) MAXIMO,
         Avg(DESCONTO) MEDIA,
         Count(*) QTDE
  FROM TCONTRATO
  GROUP BY Trunc(DATA);

SELECT * FROM V_CONTRATO;

--PODEMOS APAGAR OS SELECTS OU SCRIPTS, POIS AS VIEWS FICAM SALVAS NO BANCO (F3 - VIEWS)
--CLICAR NA VIEW DA LISTA COM O BOTÃO DIREITO EM SEGUIDA CLICA EM LOAD DLL.
--OU SELECIONA O NOME DA VIEW E CTRL+F12 OU CTRL+SHIFT+F12


---CONTINUAÇÃO 26/06/2018

--VIEW SIMPLES
--CRIANDO UMA VIEW PARA LISTAR APENAS PESSOAS TIPO FÍSICAS
CREATE OR REPLACE VIEW V_PESSOA_F
AS
  SELECT COD_PESSOA, TIPO, NOME, COD_RUA AS RUA
  FROM TPESSOA
  WHERE TIPO = 'F';

SELECT * FROM V_PESSOA_F;

--EXEMPLO DE CONSULTA USANDO VIEW E TABELA
--ENVOLVENDO TABELA TRUA E TCIDADE.
SELECT PES.COD_PESSOA AS CODIGO,
       PES.NOME AS PESSOA,
       CID.NOME AS CIDADE,
       RUA.NOME AS RUA
FROM V_PESSOA_F PES, TRUA RUA, TCIDADE CID
WHERE PES.RUA = RUA.COD_RUA(+)
AND CID.COD_CIDADE = RUA.COD_CIDADE
ORDER BY PES.NOME;

--OPERAÇÃO DML NA VIEW
--INSERIR REGISTROS COM VALORES = 1000
CREATE OR REPLACE VIEW VCURSOS1000CK
  AS
    SELECT COD_CURSO, NOME, VALOR
    FROM TCURSO
    WHERE VALOR = 1000
    WITH CHECK OPTION CONSTRAINT VCURSO1000_CK;


--VALOR NAO SERA INSERIDO
INSERT INTO VCURSOS1000CK
  (COD_CURSO, NOME, VALOR)
VALUES(52,'TESTE Y',900);

--VALOR SERÉ INSERIDO
--ATRAVÉS DA VIEW OS DADOS SÃO INSERIDOS NA TABELA, NÃO SÃO INSERIDOS NA TABELA VIEW.
INSERT INTO VCURSOS1000CK
  (COD_CURSO, NOME, VALOR)
VALUES(52,'TESTE Y',1000);

SELECT * FROM TCURSO;

--DELETE VIEW
--OS DADOS SERÃO EXCLUÍDOS NA TABELA TALUNO E NA TABELA VIEW_ALUNO
DELETE FROM V_ALUNO WHERE CODIGO = 3;

SELECT * FROM V_ALUNO;
SELECT * FROM TALUNO;

--INSERT EM VIEW
INSERT INTO V_ALUNO
VALUES(50,500,'MARIA','RS','NH');

COMMIT;

--DELETE UMA VIEW
--NÃO É PERMITIDO DELETAR UMA VIEW COMPLEXA, APENAS VIEW SIMPLES
DELETE FROM V_CONTRATO;

--VIEW SOMENTE LEITURA (NÃO PERMITE DML)- PORQUE USAREMOS A CLÁUSULA WITH COM READ ONLY
CREATE OR REPLACE VIEW V_ALUNO3
AS
  SELECT COD_ALUNO CODIGO,
         NOME ALUNO, CIDADE
  FROM TALUNO
  WHERE ESTADO = 'RS'
  WITH READ ONLY;

--NÃO PODE EXECUTAR DELETE EM VIEW SOMENTE LEITURA
DELETE FROM V_ALUNO3;

--EXCLUINDO VISÃO
DROP VIEW V_ALUNO3;

COMMIT;