SELECT * FROM TALUNO;

SELECT COD_ALUNO, NOME, CIDADE FROM TALUNO;

SELECT COD_ALUNO AS "Codigo do Aluno", NOME AS "Nome do Aluno" FROM taluno;

SELECT CIDADE FROM TALUNO;

INSERT INTO TALUNO VALUES(4,'Maria','Canoas','48884939');
INSERT INTO TALUNO VALUES(5,'Paulo','CANOAS','488847');

SELECT DISTINCT CIDADE FROM TALUNO;

SELECT * FROM TCURSO;

SELECT NOME AS
  CURSO,
  VALOR,
  VALOR/CARGA_HORARIA,
  Round(VALOR/CARGA_HORARIA,2) AS VALOR_HORA
FROM TCURSO
ORDER BY VALOR_HORA;

SELECT * FROM TCONTRATO;

UPDATE TCONTRATO SET DESCONTO = NULL WHERE COD_CONTRATO = 1;

ROLLBACK;

SELECT COD_CONTRATO,
  TOTAL,
  DESCONTO,
  TOTAL+Nvl(DESCONTO,0) AS "TOTAL COM DESCONTO"
FROM TCONTRATO;


SELECT COD_ALUNO || ' - ' || NOME || ' // ' || CIDADE AS ALUNO
FROM TALUNO
ORDER BY COD_ALUNO;

