--CAPÍTULO 9

CREATE TABLE TESTE
(
  CODIGO INTEGER NOT NULL PRIMARY KEY,
  DATA DATE DEFAULT SYSDATE
);

INSERT INTO TESTE (CODIGO) VALUES(1);
INSERT INTO TESTE (CODIGO) VALUES(2);

SELECT * FROM TESTE;


--TABELAS CRIADAS PELO USUARIO - USER_TABLES (View)
SELECT * FROM USER_TABLES;
SELECT * FROM ALL_TABLES;


--CRIAR UMA TABELAS A PARTIR DE UMA OUTRA TABELA DE DE UM RESULTADO
CREATE TABLE TCONTRATO_VIP
AS
  SELECT * FROM TCONTRATO WHERE TOTAL > 500;

SELECT * FROM TCONTRATO_VIP;

--ADD COLUNA NA TABELA
ALTER TABLE TCONTRATO_VIP ADD VALOR NUMBER(5,2); -- 999,99

--ALTERAR COLUNA
ALTER TABLE TCONTRATO_VIP MODIFY VALOR NUMBER(8,2); -- 999999,99

--ALTERAR COLUNA
ALTER TABLE TCONTRATO_VIP MODIFY VALOR NUMBER(12,2) DEFAULT 0;

--RENOMEAR COLUNA
ALTER TABLE TCONTRATO_VIP RENAME COLUMN VALOR TO VALOR2;

--EXCLUIR COLUNA
ALTER TABLE TCONTRATO_VIP DROP COLUMN VALOR2;

--EXCLUIR TABELA
DROP TABLE TCONTRATO_VIP;



--COMENTÁRIOS NA TABELA
COMMENT ON TABLE TCONTRATO IS 'Informações de Contratos'; --É POSSIVEL VER NA ESTRUTURA DE EXPORTAÇÃO DA TABELA

--COMENTÁRIO NA COLUNA DA TABLEA
COMMENT ON COLUMN TCONTRATO.COD_CONTRATO IS 'Código do Contrato'; --SELECIONA A TABELA E DA F12
COMMENT ON COLUMN TCONTRATO.DATA IS 'Data de emissão do Contrato';

SELECT * FROM USER_COL_COMMENTS WHERE TABLE_NAME = 'TCONTRATO';
SELECT * FROM USER_TAB_COMMENTS WHERE TABLE_NAME = 'TCONTRATO';

--DESABILITA A COLUNA
ALTER TABLE TCONTRATO ADD TOTAL2 NUMERIC(8,2);

ALTER TABLE TCONTRATO SET UNUSED (TOTAL2);--NÃO TEM COMO HABILITAR, APÓS ISSO, SÓ DROPANDO A COLUNA.






