--CAPÍTULO 9

CREATE TABLE TESTE
(
  CODIGO INTEGER NOT NULL PRIMARY KEY,
  DATA DATE DEFAULT SYSDATE
);

INSERT INTO TESTE (CODIGO) VALUES(1);
INSERT INTO TESTE (CODIGO) VALUES(2);

SELECT * FROM TESTE;


--TABELAS CRIADAS PELO USUARIO - USER_TABLES (View)
SELECT * FROM USER_TABLES;
SELECT * FROM ALL_TABLES;


--CRIAR UMA TABELAS A PARTIR DE UMA OUTRA TABELA DE DE UM RESULTADO
CREATE TABLE TCONTRATO_VIP
AS
  SELECT * FROM TCONTRATO WHERE TOTAL > 500;

SELECT * FROM TCONTRATO_VIP;

--ADD COLUNA NA TABELA
ALTER TABLE TCONTRATO_VIP ADD VALOR NUMBER(5,2); -- 999,99

--ALTERAR COLUNA
ALTER TABLE TCONTRATO_VIP MODIFY VALOR NUMBER(8,2); -- 999999,99

--ALTERAR COLUNA
ALTER TABLE TCONTRATO_VIP MODIFY VALOR NUMBER(12,2) DEFAULT 0;

--RENOMEAR COLUNA
ALTER TABLE TCONTRATO_VIP RENAME COLUMN VALOR TO VALOR2;

--EXCLUIR COLUNA
ALTER TABLE TCONTRATO_VIP DROP COLUMN VALOR2;

--EXCLUIR TABELA
DROP TABLE TCONTRATO_VIP;



--COMENTÁRIOS NA TABELA
COMMENT ON TABLE TCONTRATO IS 'Informações de Contratos'; --É POSSIVEL VER NA ESTRUTURA DE EXPORTAÇÃO DA TABELA

--COMENTÁRIO NA COLUNA DA TABLEA
COMMENT ON COLUMN TCONTRATO.COD_CONTRATO IS 'Código do Contrato'; --SELECIONA A TABELA E DA F12
COMMENT ON COLUMN TCONTRATO.DATA IS 'Data de emissão do Contrato';

SELECT * FROM USER_COL_COMMENTS WHERE TABLE_NAME = 'TCONTRATO';
SELECT * FROM USER_TAB_COMMENTS WHERE TABLE_NAME = 'TCONTRATO';

--DESABILITA A COLUNA
ALTER TABLE TCONTRATO ADD TOTAL2 NUMERIC(8,2);

ALTER TABLE TCONTRATO SET UNUSED (TOTAL2);--NÃO TEM COMO HABILITAR, APÓS ISSO, SÓ DROPANDO A COLUNA.

-- 17/06/2018 - Continuação
-- CONSTRAINTS
TALUNO
  COD_ALUNO - PK -> Chave Primária -> PRIMARY KEY
TCONTRATO
  COD_CONTRATO - PK -> Chave Primária -> PRIMARY KEY
  COD_ALUNO - FK -> Chave primária que vem de outra tabela

SELECT * FROM USER_CONSTRAINTS;  --CONSTRAINTS DO USUÁRIO
SELECT * FROM ALL_CONSTRAINTS;   --CONSTRAINTS DO BD

CREATE TABLE TCIDADE(
  COD_CIDADE  INTEGER NOT NULL,      --PRIMARY KEY - FAREMOS NA CONSTRAINT
  NOME VARCHAR(40),
  CONSTRAINT PK_CIDADE PRIMARY KEY(COD_CIDADE)
);

SELECT * FROM TCIDADE;
SELECT * FROM LESTADO;
SELECT * FROM LCIDADE;

ALTER TABLE TESTADO RENAME TO LESTADO;
ALTER TABLE TCIDADE RENAME TO LCIDADE;

CREATE TABLE TBAIRRO(
  COD_CIDADE INTEGER NOT NULL,
  COD_BAIRRO INTEGER NOT NULL,
  NOME VARCHAR2(40),
  CONSTRAINT PK_BAIRRO PRIMARY KEY(COD_CIDADE, COD_BAIRRO)
);
--CRIAMOS UMA CHAVE PRIMÁRIA MULTIPLA
/*
CIDADE  BAIRRO
1       1
1       2
2       1
2       2
2       2 - NÃO PODERÁ SER ACEITO POIS JÁ EXISTE ESSES VALORES NAS DUAS COLUNAS
*/


SELECT * FROM TBAIRRO;
SELECT * FROM TCIDADE;

--LIGANDO AS DUAS TABELAS E ADICIONANDO UMA CHAVE ESTRANGEIRA
ALTER TABLE TBAIRRO ADD CONSTRAINT FK_COD_CIDADE --ALTERAR A TABELA FILHA
FOREIGN KEY (COD_CIDADE) --COD_CIDADE DA TABELA TBAIRRO
REFERENCES TCIDADE(COD_CIDADE); --FAZ REFERÊNCIA A COD_CIDADE DA TABELA TCIDADE.

--PODE FAZER ESSA CONSTRAINT JUNTO OU SEPARADO COMO FIZEMOS


CREATE TABLE TRUA(
  COD_RUA INTEGER NOT NULL,
  COD_CIDADE INTEGER,
  COD_BAIRRO INTEGER,
  NOME VARCHAR(40),
  CONSTRAINT PK_RUA PRIMARY KEY(COD_RUA)
);

SELECT * FROM TRUA;

ALTER TABLE TRUA ADD CONSTRAINT FK_CIDADEBAIRRO
FOREIGN KEY(COD_CIDADE, COD_BAIRRO)
REFERENCES TBAIRRO(COD_CIDADE, COD_BAIRRO);

--QUALQUER TABELA QUE SEJA LIGADA A TBAIRRO, TEM QUE SER DE DUAS COLUNAS, POIS A TBAIRRO POSSUI UMA CHAVE PRIMÁRIA DE DUAS COLUNAS

CREATE TABLE TPESSOA(
  COD_PESSOA  INTEGER NOT NULL,
  TIPO  VARCHAR2(1) NOT NULL,
  NOME  VARCHAR2(30)  NOT NULL,
  PESSOA VARCHAR2(1)  NOT NULL,
  COD_RUA INTEGER NOT NULL,
  CPF VARCHAR2(15),
  CONSTRAINT PK_PESSOA PRIMARY KEY (COD_PESSOA)
);

--UNIQUE KEY
ALTER TABLE TPESSOA ADD CONSTRAINT UK_CPF UNIQUE(CPF); --RESTRINÇÃO PARA DENTRO DA TABELA

--ALTER TABLE TPESSOA DROP CONSTRAINT NOME CONSTRAINT
ALTER TABLE TPESSOA ADD CONSTRAINT FK_PESSOA_RUA  --RESTRINÇÃO QUE SE REFERE A VALORES FORA DA TABELA
FOREIGN KEY (COD_RUA)
REFERENCES TRUA; --NÃO PRECISA ESPECIFICAR CAMPO, POIS SO PODE FAZER REFERENCIA AO CAMPO COM CHAVE PRIMARIA (DARIA ERRO SE NÃO TIVESSE CHAVE PRIMARIA NA TABELA PAI)

--CIDADE
INSERT INTO TCIDADE VALUES(1,'NOVO HAMBURGO');
INSERT INTO TCIDADE VALUES(2,'IVOTI');
INSERT INTO TCIDADE VALUES(3,'SAPIRANGA');
INSERT INTO TCIDADE VALUES(4,'TAQUARA');

SELECT * FROM TCIDADE;

--BAIRRO
INSERT INTO TBAIRRO VALUES(1,1,'CENTRO');
INSERT INTO TBAIRRO VALUES(2,1,'RIO BRANCO');
INSERT INTO TBAIRRO VALUES(3,1,'CENTRO');
INSERT INTO TBAIRRO VALUES(4,1,'FRITZ');
INSERT INTO TBAIRRO VALUES(5,1,'AMARAL'); --FK NAO DEIXA INSERIR FILHO SEM PAI
INSERT INTO TBAIRRO VALUES(6,1,'EMPRESA');
--SE TENTAR EXCLUIR CIDADE, NAO VAI DEIXAR, POIS EXISTE FILHO AMARRADO A CIDADE

SELECT * FROM TBAIRRO;

--RUA
INSERT INTO TRUA VALUES(1,1,1,'MARCILIO DIAS');
INSERT INTO TRUA VALUES(2,2,1,'FRITZ');
INSERT INTO TRUA VALUES(3,3,1,'JACOBINA');
INSERT INTO TRUA VALUES(4,3,1,'JOAO DA SILVA');

SELECT * FROM TRUA;

--TIPO DE RESTRIÇÃO CHECK
ALTER TABLE TPESSOA ADD CONSTRAINT CK_PESSOA_TIPO
CHECK (TIPO IN('C','F'));

ALTER TABLE TPESSOA ADD CONSTRAINT CK_PESSOA_JS
CHECK (PESSOA IN('J','F'));

--EXCLUIR CONSTRAINT
ALTER TABLE DROP CONSTRAINT NOME_CONSTRAINT;

--INSERIR PESSOAS
INSERT INTO TPESSOA VALUES(1,'C','MARCIO','F',1,'1234');
INSERT INTO TPESSOA VALUES(2,'F','BEATRIZ','F',2,'123');
INSERT INTO TPESSOA VALUES(3,'F','PEDRO','F',4,'12345');
INSERT INTO TPESSOA VALUES(4,'C','MARIA','J',4,'123456');


SELECT * FROM TPESSOA;

COMMIT;