--Capítulo 7 - Sub-consultas
SELECT COD_CONTRATO, DATA, TOTAL
FROM TCONTRATO
WHERE TOTAL <=
  (SELECT VALOR FROM TCURSO
   WHERE COD_CURSO = 1);

--Errado (Só pode retornar 1 Linha na subconsulta)
SELECT COD_CONTRATO, DATA, TOTAL
FROM TCONTRATO
WHERE TOTAL >=
  (SELECT VALOR FROM TCURSO
   WHERE VALOR > 500);

--Consultar os Alunos da Mesma cidade do Aluno 1
--Menos o Aluno 1
SELECT COD_ALUNO, NOME, CIDADE
FROM TALUNO
WHERE CIDADE = (SELECT CIDADE FROM TALUNO
                WHERE COD_ALUNO = 1)
AND COD_ALUNO <> 1;

--AO COMPARAR COLUNAS EM SUBCONSULTA, DEVEMOS USAR A MESMA QUANTIDADE DE COLUNA
--CONSULTAREMOS A CIDADE E O ESTADO NAS DUAS TABELAS, MENOS O ALUNO DE CODIGO 1
SELECT COD_ALUNO, NOME, CIDADE, ESTADO
FROM TALUNO
WHERE (CIDADE,ESTADO) =
      (SELECT CIDADE, ESTADO FROM TALUNO
       WHERE COD_ALUNO = 1)
AND COD_ALUNO <> 1;

--CONSULTAREMOS A CIDADE E O ESTADO E O CEP, PORÉM NÃO RETORNAR RESULTADO POIS NENHUMA TEM O MESMO CEP, MENOS O ALUNO DE CODIGO 1
SELECT COD_ALUNO, NOME, CIDADE, ESTADO
FROM TALUNO
WHERE (CIDADE,ESTADO, CEP) =
      (SELECT CIDADE, ESTADO, CEP FROM TALUNO
       WHERE COD_ALUNO = 1)
AND COD_ALUNO <> 1;

--USANDO HAVING EM SUBCONSULTA PARA FUNÇAO
SELECT COD_CURSO, Min(VALOR), Sum(VALOR), Count(*) QTDE
FROM TITEM
WHERE COD_CURSO > 0
GROUP BY COD_CURSO
HAVING Min(VALOR) >=   --ESSE CRITÉRIO
       (SELECT Avg(VALOR) FROM TCURSO) --DEPENDE DESSE CRITÉRIO E VICE-VERSA.
ORDER BY COD_CURSO;

--SOMAR O TOTAL DE CONTRATO POR ALUNO E MOTRAR SOMENTE
--CUJO O MENOR CONTRATO SEJA MAIOR QUE O VALOR DO CUSTO MÉDIO;
SELECT COD_ALUNO, Min(TOTAL), Sum(TOTAL)
FROM TCONTRATO
GROUP BY COD_ALUNO
HAVING Min(TOTAL) >
    (SELECT Avg(VALOR) FROM TCURSO);

--TODOS OS CURSOS QUE ESTÃO NA TABELA DE
--ITEM (VENDIDOS)

SELECT COD_CURSO, NOME, VALOR
FROM TCURSO
WHERE COD_CURSO IN
  (SELECT COD_CURSO FROM TITEM);


--TOOS OS CURSOS QUE NÃO ESTÃO NA TABELA DE ITEM
--(NÃO VENDIDOS)
--AGRUPANDO OS CURSOS
SELECT COD_CURSO, NOME, VALOR
FROM TCURSO
WHERE COD_CURSO IN
  (SELECT COD_CURSO FROM TITEM)
ORDER BY NOME;

--06/06/208 - Continua
--CÓDIGO EQUIVALENTE A SUBSELECT (SE OS VALORES SAO CONHECIDOS) - NÃO É A MANEIRA EFICIENTE OU MAIS CORRETA.
SELECT COD_CURSO, NOME, VALOR
FROM TCURSO WHERE COD_CURSO IN (1,2,3,4);

--OU
SELECT COD_CURSO, NOME, VALOR
FROM TCURSO
WHERE COD_CURSO = 1 OR COD_CURSO = 2 OR COD_CURSO = 3;

--TODOS OS CURSOS QUE FORAM VENDIDOS, PELO VALOR PADRÃO.
SELECT * FROM TITEM
WHERE (COD_CURSO, VALOR) IN
      (SELECT COD_CURSO, VALOR FROM TCURSO);

--SUBCONSULTA NA CLÁUSULA FROM
SELECT ITE.COD_CONTRATO, ITE.VALOR,
       ITE.COD_CURSO,
       CUR.COD_CURSO AS CODIGO, CUR.VALOR
FROM TITEM ITE,
      (SELECT COD_CURSO, VALOR       --SEGUNDA TABELA É UMA SUBCONSULTA
       FROM TCURSO WHERE VALOR > 500) CUR

WHERE CUR.COD_CURSO = ITE.COD_CURSO;




SELECT * FROM TITEM;
SELECT * FROM TALUNO;
SELECT * FROM TCONTRATO;
SELECT * FROM TCURSO;




