--CAPÍTULO 11 -- 22/06/2018

--CRIANDO UMA VIEW
CREATE OR REPLACE VIEW V_ALUNO
AS
  SELECT COD_ALUNO AS CODIGO,
         SALARIO,
         NOME AS ALUNO,
         ESTADO,
         CIDADE
  FROM TALUNO
  WHERE ESTADO = 'RS';
  --SELECT QUE REPRESENTA ESSA VIEW

--USANDO A VIEW
SELECT * FROM V_ALUNO
ORDER BY ALUNO;

--VIEW CONTRATO_TOP
CREATE OR REPLACE VIEW V_CONTRATO_TOP
AS
  SELECT COD_CONTRATO, DESCONTO
  FROM TCONTRATO
  WHERE DESCONTO >= 10;

--USANDO A VIEW CONTRATO_TOP
SELECT * FROM V_CONTRATO_TOP;

--NOME E CONTEÚDO DAS VIEWS
SELECT VIEW_NAME, TEXT
FROM USER_VIEWS;--VIEW QUE MOSTRA OUTRAS VIEWS.

--VIEW COM PARÂMETRO DE SAÍDA
CREATE OR REPLACE VIEW V_ALUNO2(COD, ALUNO, SAL)
AS
  SELECT COD_ALUNO, NOME, SALARIO
  FROM TALUNO;

SELECT * FROM V_ALUNO2;

--VIEW COMPLEXA - A CARACTERISTICA DESSA VIEW QUE A FAZ SER COMPLEXA, NAO QUE SEJA COMPLEXA
CREATE OR REPLACE VIEW V_CONTRATO
AS
  SELECT Trunc(DATA) AS DATA,
         Max(DESCONTO) MAXIMO,
         Avg(DESCONTO) MEDIA,
         Count(*) QTDE
  FROM TCONTRATO
  GROUP BY Trunc(DATA);

SELECT * FROM V_CONTRATO;

--PODEMOS APAGAR OS SELECTS OU SCRIPTS, POIS AS VIEWS FICAM SALVAS NO BANCO (F3 - VIEWS)
--CLICAR NA VIEW DA LISTA COM O BOTÃO DIREITO EM SEGUIDA CLICA EM LOAD DLL.
--OU SELECIONA O NOME DA VIEW E CTRL+F12 OU CTRL+SHIFT+F12
