--SEQUENCE - OUTROS OBJETOS DO BANCO

CREATE SEQUENCE SEQ_ALUNO1
START WITH 60
--valor inicial
INCREMENT BY 5
--Qtde a Incrementar
MINVALUE 60
--Valor Mínimo
MAXVALUE 250
--Valor Máximo
NOCACHE
--Não guarda em cache faixa de valores -- PADRÃO É 20
NOCYCLE;
--QUANDO CHEGAR EM 250 ELE VOLTARIA PRA 60, MAS NÃO FARÁ.
--USO RARO

INSERT INTO TALUNO (COD_ALUNO, NOME)
VALUES (SEQ_ALUNO1.NEXTVAL,'MASTER TRAINING');

INSERT INTO TALUNO (COD_ALUNO, NOME)
VALUES (SEQ_ALUNO1.NEXTVAL,'MASTER TRAINING 2');

SELECT * FROM TALUNO;

SELECT * FROM USER_SEQUENCES;
--EXIBE A TABELA COM SEQUENCES DO USUARIO

--VALOR ATUAL DA SEQUENCE
SELECT SEQ_ALUNO1.CURRVAL FROM DUAL;

--ALTERAR SEQUENCE
ALTER SEQUENCE SEQ_ALUNO1 MAXVALUE 500;
ALTER SEQUENCE SEQ_ALUNO1 INCREMENT BY 2;

--ALTERAR VALOR DA SEQUENCIA
--APAGA
DROP SEQUENCE SEQ_ALUNO1;
--CRIA NOVAMENTE
CREATE SEQUENCE SEQ_ALUNO1 START WITH 80;






