
SELECT * FROM TALUNO;

--Produto Cartesiano -> ERRADO
SELECT TALUNO.COD_ALUNO, TALUNO.NOME, TCONTRATO.TOTAL
FROM TALUNO, TCONTRATO;


--Falta Critério de União das duas Tabelas.
--Forma correta.
SELECT TALUNO.COD_ALUNO, TALUNO.NOME, TCONTRATO.TOTAL
FROM TALUNO, TCONTRATO
--CRITÉRIO DE UNIÃO
WHERE TALUNO.COD_ALUNO = TCONTRATO.COD_ALUNO;


--Errado - Coluna Ambígua
--Correto: quando uma coluna existe com o mesmo nome em uma tabela,
--colocar prefixo na coluna.

SELECT COD_ALUNO, TALUNO.NOME, TCONTRATO.TOTAL
FROM TALUNO, TCONTRATO
WHERE TALUNO.COD_ALUNO = TCONTRATO.COD_ALUNO;


--Dando apelido a tabela
SELECT ALU.COD_ALUNO, ALU.NOME AS ALUNO,
       CON.COD_CONTRATO, CON.DATA, CON.TOTAL

FROM TALUNO ALU, TCONTRATO CON

WHERE CON.COD_ALUNO = ALU.COD_ALUNO --Critério de união

AND Upper(ALU.NOME) LIKE '%' --Filtro

ORDER BY ALU.NOME; --Ordenar por nome



SELECT ALU.CODIGO, ALU.NOME AS ALUNO,
       CON.COD_CONTRATO, CON.DATA, CON.TOTAL,
       ITE.COD_CURSO, CUR.NOME AS CURSO,
       ITE.VALOR
FROM TALUNO ALU, TCONTRATO CON,
     TITEM ITE, TCURSO CUR

WHERE ALU.COD_ALUNO = CON.COD_ALUNO(+) --Critério de União
AND CON.COD_CONTRATO = ITE.COD_ITEM(+)
AND ITE.COD_CURSO = CUR.COD_CURSO(+);


ALTER TABLE TITEM ADD COD_CURSO INTEGER;
SELECT * FROM TITEM;

UPDATE TITEM SET COD_CURSO = 1 WHERE COD_ITEM = 1;
UPDATE TITEM SET COD_CURSO = 3 WHERE COD_ITEM = 8;
INSERT INTO TITEM(COD_ITEM, ITEM, DOC_CURSO, COD_CURSO) VALUES (6, CURSO 1);
DROP TABLE TITEM;

DROP SEQUENCE SEQ_TITEM;

CREATE TABLE TITEM
(
  COD_ITEM INTEGER NOT NULL PRIMARY KEY,
  COD_CURSO INTEGER ,
  COD_CONTRATO INTEGER,
  VALOR NUMBER (8,2)
 );
SELECT * FROM TITEM;

CREATE SEQUENCE SEQ_TITEM START WITH 1;

DELETE FROM TITEM;

INSERT INTO TITEM VALUES(SEQ_TITEM.NEXTVAL,1,1,500);
INSERT INTO TITEM VALUES(SEQ_TITEM.NEXTVAL,1,2,500);
INSERT INTO TITEM VALUES(SEQ_TITEM.NEXTVAL,3,3,1500);
INSERT INTO TITEM VALUES(SEQ_TITEM.NEXTVAL,4,4,1500);
INSERT INTO TITEM VALUES(SEQ_TITEM.NEXTVAL,1,6,500);
INSERT INTO TITEM VALUES(SEQ_TITEM.NEXTVAL,2,6,500);
INSERT INTO TITEM VALUES(SEQ_TITEM.NEXTVAL,3,7,500);

SELECT * FROM TITEM;


--SELECT COM 4 TABELAS
SELECT * FROM TALUNO;
SELECT * FROM TCONTRATO;
SELECT * FROM TITEM;
SELECT * FROM TCURSO;


SELECT ALU.COD_ALUNO, ALU.NOME AS ALUNO,
       CON.COD_CONTRATO, CON.DATA, CON.TOTAL,
       ITE.COD_CURSO, CUR.NOME AS CURSO,
       ITE.VALOR

FROM TALUNO ALU, TCONTRATO CON,
       TITEM ITE, TCURSO CUR

WHERE ALU.COD_ALUNO = CON.COD_ALUNO --Critério Uniã
AND CON.COD_CONTRATO = ITE.COD_CONTRATO
AND ITE.COD_CURSO = CUR.COD_CURSO

ORDER BY CON.TOTAL DESC;

SELECT * FROM TALUNO;
INSERT INTO TALUNO VALUES(10, 'PEDRO','NOVO HAMBURGO', NULL);
